//! Rust-native Jules index generator.
//!
//! Generates the durable rollup files under `.jules/index/generated/` from
//! live run packets, historical ledgers, and open friction records.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde_json::Value;

use crate::cli::JulesIndexArgs;

const RUNS_ROLLUP: &str = ".jules/index/generated/RUNS_ROLLUP.md";
const FRICTION_ROLLUP: &str = ".jules/index/generated/FRICTION_ROLLUP.md";

#[derive(Debug, Clone)]
struct RunRow {
    id: String,
    persona: String,
    style: String,
    shard: String,
    status: String,
    gates_run: usize,
    source: String,
}

#[derive(Debug, Clone)]
struct FrictionRow {
    id: String,
    persona: String,
    style: String,
    shard: String,
    status: String,
    summary: String,
}

pub fn run(args: JulesIndexArgs) -> Result<()> {
    let root = workspace_root()?;
    let outputs = [
        (root.join(RUNS_ROLLUP), render_runs_rollup(&root)?),
        (root.join(FRICTION_ROLLUP), render_friction_rollup(&root)?),
    ];

    if args.check {
        let mut stale = Vec::new();
        for (path, expected) in &outputs {
            let actual = fs::read_to_string(path).unwrap_or_default();
            if actual != *expected {
                stale.push(path.display().to_string());
            }
        }
        if stale.is_empty() {
            println!("jules-index OK: generated indexes are up to date");
            return Ok(());
        }
        for path in &stale {
            eprintln!("stale: {path}");
        }
        bail!("jules-index: {} generated file(s) are stale", stale.len());
    }

    for (path, body) in &outputs {
        let parent = path
            .parent()
            .with_context(|| format!("resolve parent for {}", path.display()))?;
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
        fs::write(path, body).with_context(|| format!("write {}", path.display()))?;
    }
    println!("jules-index: wrote {RUNS_ROLLUP} and {FRICTION_ROLLUP}");
    Ok(())
}

fn render_runs_rollup(root: &Path) -> Result<String> {
    let runs = collect_runs(root)?;
    let mut out = String::new();
    out.push_str("# Generated Run Index\n\n");
    out.push_str("This file is automatically generated by `cargo xtask jules-index`.\n");
    out.push_str(
        "It rolls up metadata from all run packets in `.jules/runs/` and historical ledgers.\n\n",
    );
    out.push_str("| Run ID | Persona | Style | Shard | Status | Gates Run | Source |\n");
    out.push_str("|---|---|---|---|---|---|---|\n");
    for run in runs {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} | {} |\n",
            run.id,
            markdown_cell(&run.persona),
            markdown_cell(&run.style),
            markdown_cell(&run.shard),
            markdown_cell(&run.status),
            run.gates_run,
            markdown_cell(&run.source)
        ));
    }
    Ok(out)
}

fn render_friction_rollup(root: &Path) -> Result<String> {
    let items = collect_friction(root)?;
    let mut out = String::new();
    out.push_str("# Generated Friction Index\n\n");
    out.push_str("This file is automatically generated by `cargo xtask jules-index`.\n");
    out.push_str("It rolls up active friction metadata from `.jules/friction/open/`.\n\n");
    out.push_str("| ID | Persona | Style | Shard | Status | Summary |\n");
    out.push_str("|---|---|---|---|---|---|\n");
    for item in items {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            markdown_cell(&item.id),
            markdown_cell(&item.persona),
            markdown_cell(&item.style),
            markdown_cell(&item.shard),
            markdown_cell(&item.status),
            markdown_cell(&item.summary)
        ));
    }
    Ok(out)
}

fn collect_runs(root: &Path) -> Result<Vec<RunRow>> {
    let mut runs = Vec::new();
    collect_live_runs(root, &mut runs)?;
    collect_docs_runs(root, &mut runs)?;
    collect_quality_runs(root, &mut runs)?;
    Ok(runs)
}

fn collect_live_runs(root: &Path, runs: &mut Vec<RunRow>) -> Result<()> {
    let runs_dir = root.join(".jules/runs");
    if !runs_dir.exists() {
        return Ok(());
    }

    let mut entries = fs::read_dir(&runs_dir)
        .with_context(|| format!("read {}", runs_dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let id = entry.file_name().to_string_lossy().to_string();
        let run_path = entry.path();
        let envelope = read_json(&run_path.join("envelope.json"));
        let result = read_json(&run_path.join("result.json"));
        runs.push(RunRow {
            id,
            persona: value_string(&envelope, "persona", "Unknown"),
            style: value_string(&envelope, "style", "Unknown"),
            shard: value_string(&envelope, "primary_shard", "Unknown"),
            status: value_string(&result, "status", "in-progress"),
            gates_run: value_array_len(&result, "gates_run"),
            source: "live".to_string(),
        });
    }
    Ok(())
}

fn collect_docs_runs(root: &Path, runs: &mut Vec<RunRow>) -> Result<()> {
    let docs_ledger = read_json(&root.join(".jules/docs/ledger.json"));
    let Some(entries) = docs_ledger.as_array() else {
        return Ok(());
    };

    for entry in entries.iter().filter_map(Value::as_object) {
        let run_id = map_string(entry, "run_id", "Unknown");
        let env_path = root
            .join(".jules/docs/envelopes")
            .join(format!("{run_id}.json"));
        let env_data = read_json(&env_path);
        let env = env_data.as_object();
        runs.push(RunRow {
            id: run_id,
            persona: first_non_empty(&[
                env.and_then(|m| m.get("persona")).and_then(Value::as_str),
                entry.get("persona").and_then(Value::as_str),
                entry.get("lane").and_then(Value::as_str),
            ]),
            style: first_non_empty(&[
                env.and_then(|m| m.get("style")).and_then(Value::as_str),
                entry.get("style").and_then(Value::as_str),
            ]),
            shard: first_non_empty(&[
                env.and_then(|m| m.get("primary_shard"))
                    .and_then(Value::as_str),
                entry.get("target").and_then(Value::as_str),
            ]),
            status: "historical".to_string(),
            gates_run: env
                .and_then(|m| m.get("receipts"))
                .or_else(|| entry.get("receipts"))
                .and_then(Value::as_array)
                .map_or(0, Vec::len),
            source: "docs".to_string(),
        });
    }
    Ok(())
}

fn collect_quality_runs(root: &Path, runs: &mut Vec<RunRow>) -> Result<()> {
    let quality_ledger = read_json(&root.join(".jules/quality/ledger.json"));
    let Some(entries) = quality_ledger.get("runs").and_then(Value::as_array) else {
        return Ok(());
    };

    for entry in entries.iter().filter_map(Value::as_object) {
        let run_id = map_string(entry, "run_id", "Unknown");
        let env_path = root
            .join(".jules/quality/envelopes")
            .join(format!("{run_id}.json"));
        let env_data = read_json(&env_path);
        let env = env_data.as_object();
        let description = entry
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or_default();
        let mut persona =
            first_non_empty(&[env.and_then(|m| m.get("persona")).and_then(Value::as_str)]);
        if persona == "Unknown" && description.contains("Gatekeeper") {
            persona = "Gatekeeper".to_string();
        }
        runs.push(RunRow {
            id: run_id,
            persona,
            style: first_non_empty(&[env.and_then(|m| m.get("style")).and_then(Value::as_str)]),
            shard: first_non_empty(&[
                env.and_then(|m| m.get("primary_shard"))
                    .and_then(Value::as_str),
                entry.get("target").and_then(Value::as_str),
            ]),
            status: "historical".to_string(),
            gates_run: env
                .and_then(|m| m.get("receipts"))
                .or_else(|| entry.get("receipts"))
                .and_then(Value::as_array)
                .map_or(0, Vec::len),
            source: "quality".to_string(),
        });
    }
    Ok(())
}

fn collect_friction(root: &Path) -> Result<Vec<FrictionRow>> {
    let friction_dir = root.join(".jules/friction/open");
    if !friction_dir.exists() {
        return Ok(Vec::new());
    }

    let mut paths = fs::read_dir(&friction_dir)
        .with_context(|| format!("read {}", friction_dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()?;
    paths.sort_by_key(|entry| entry.file_name());

    let mut items = Vec::new();
    for entry in paths {
        if entry.path().extension().and_then(|ext| ext.to_str()) == Some("md") {
            items.push(friction_metadata(&entry.path())?);
        }
    }
    Ok(items)
}

fn friction_metadata(path: &Path) -> Result<FrictionRow> {
    let content = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let lines: Vec<&str> = content.lines().collect();
    let mut metadata = BTreeMap::from([
        ("persona".to_string(), "Unknown".to_string()),
        ("style".to_string(), "Unknown".to_string()),
        ("shard".to_string(), "Unknown".to_string()),
        ("status".to_string(), "open".to_string()),
        ("summary".to_string(), String::new()),
    ]);

    for line in lines.iter().take(24) {
        let stripped = line.trim().trim_matches('*');
        let Some((key, value)) = stripped.split_once(':') else {
            continue;
        };
        let key = key.trim().to_lowercase().replace(' ', "_");
        let value = value.trim().trim_matches('*').trim();
        if value.is_empty() {
            continue;
        }
        if metadata.contains_key(&key) {
            metadata.insert(key, value.to_string());
        } else if key == "surface" || key == "component" {
            metadata.insert("shard".to_string(), value.to_string());
        }
    }

    let summary = extract_summary(&content, &lines);
    if !summary.is_empty() {
        metadata.insert("summary".to_string(), summary);
    }

    let id = path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("Unknown")
        .to_string();

    Ok(FrictionRow {
        id,
        persona: remove_metadata(&mut metadata, "persona"),
        style: remove_metadata(&mut metadata, "style"),
        shard: remove_metadata(&mut metadata, "shard"),
        status: remove_metadata(&mut metadata, "status"),
        summary: remove_metadata(&mut metadata, "summary"),
    })
}

fn extract_summary(content: &str, lines: &[&str]) -> String {
    for heading in ["## Problem", "**Problem:**", "**Description:**"] {
        if let Some((_, after)) = content.split_once(heading)
            && let Some(summary) = after
                .lines()
                .map(|line| line.trim().trim_start_matches('-').trim())
                .find(|line| !line.is_empty())
        {
            return summary.to_string();
        }
    }

    lines
        .iter()
        .map(|line| line.trim())
        .find(|line| !line.is_empty() && !line.starts_with('#') && !line.contains(':'))
        .unwrap_or_default()
        .to_string()
}

fn remove_metadata(metadata: &mut BTreeMap<String, String>, key: &str) -> String {
    metadata.remove(key).unwrap_or_default()
}

fn read_json(path: &Path) -> Value {
    fs::read_to_string(path)
        .ok()
        .and_then(|body| serde_json::from_str(&body).ok())
        .unwrap_or(Value::Null)
}

fn value_string(value: &Value, key: &str, fallback: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .unwrap_or(fallback)
        .to_string()
}

fn value_array_len(value: &Value, key: &str) -> usize {
    value.get(key).and_then(Value::as_array).map_or(0, Vec::len)
}

fn map_string(map: &serde_json::Map<String, Value>, key: &str, fallback: &str) -> String {
    map.get(key)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .unwrap_or(fallback)
        .to_string()
}

fn first_non_empty(values: &[Option<&str>]) -> String {
    values
        .iter()
        .flatten()
        .find(|value| !value.is_empty())
        .copied()
        .unwrap_or("Unknown")
        .to_string()
}

fn markdown_cell(value: &str) -> String {
    let text = if value.trim().is_empty() {
        "Unknown".to_string()
    } else {
        value.replace('\n', " ").trim().to_string()
    };
    text.replace('|', "\\|")
}

fn workspace_root() -> Result<PathBuf> {
    let metadata = cargo_metadata::MetadataCommand::new()
        .no_deps()
        .exec()
        .context("locate workspace root")?;
    Ok(metadata.workspace_root.into_std_path_buf())
}
