//! Rust-native Jules index generator.
//!
//! This replaces the historical Python helper so Jules provenance rollups stay
//! inside the repo's Rust-first tooling surface.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_json::Value;

const UNKNOWN: &str = "Unknown";

#[derive(Debug, Clone, PartialEq, Eq)]
struct RunRow {
    id: String,
    persona: String,
    style: String,
    shard: String,
    status: String,
    gates_run: usize,
    source: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FrictionRow {
    id: String,
    persona: String,
    style: String,
    shard: String,
    status: String,
    summary: String,
}

pub fn run() -> Result<()> {
    let root = workspace_root()?;
    write_runs_rollup(&root)?;
    write_friction_rollup(&root)?;
    println!("jules-index: wrote generated Jules rollups");
    Ok(())
}

fn write_runs_rollup(repo_root: &Path) -> Result<()> {
    let output_file = repo_root.join(".jules/index/generated/RUNS_ROLLUP.md");
    let runs = collect_runs(repo_root)?;

    if let Some(parent) = output_file.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }

    let mut out = String::new();
    out.push_str("# Generated Run Index\n\n");
    out.push_str("This file is automatically generated by `cargo xtask jules-index`.\n");
    out.push_str(
        "It rolls up metadata from all run packets in `.jules/runs/` and historical ledgers.\n\n",
    );
    out.push_str("| Run ID | Persona | Style | Shard | Status | Gates Run | Source |\n");
    out.push_str("|---|---|---|---|---|---|---|\n");

    for run in runs {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} | {} |\n",
            run.id,
            markdown_cell(&run.persona),
            markdown_cell(&run.style),
            markdown_cell(&run.shard),
            markdown_cell(&run.status),
            run.gates_run,
            markdown_cell(&run.source),
        ));
    }

    fs::write(&output_file, out).with_context(|| format!("write {}", output_file.display()))
}

fn write_friction_rollup(repo_root: &Path) -> Result<()> {
    let output_file = repo_root.join(".jules/index/generated/FRICTION_ROLLUP.md");
    let friction_dir = repo_root.join(".jules/friction/open");

    let mut items = Vec::new();
    if friction_dir.exists() {
        for path in sorted_markdown_files(&friction_dir)? {
            items.push(friction_metadata(&path)?);
        }
    }

    if let Some(parent) = output_file.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }

    let mut out = String::new();
    out.push_str("# Generated Friction Index\n\n");
    out.push_str("This file is automatically generated by `cargo xtask jules-index`.\n");
    out.push_str("It rolls up active friction metadata from `.jules/friction/open/`.\n\n");
    out.push_str("| ID | Persona | Style | Shard | Status | Summary |\n");
    out.push_str("|---|---|---|---|---|---|\n");

    for item in items {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            markdown_cell(&item.id),
            markdown_cell(&item.persona),
            markdown_cell(&item.style),
            markdown_cell(&item.shard),
            markdown_cell(&item.status),
            markdown_cell(&item.summary),
        ));
    }

    fs::write(&output_file, out).with_context(|| format!("write {}", output_file.display()))
}

fn collect_runs(repo_root: &Path) -> Result<Vec<RunRow>> {
    let mut runs = Vec::new();

    let runs_dir = repo_root.join(".jules/runs");
    if runs_dir.exists() {
        for run_path in sorted_dirs(&runs_dir)? {
            let envelope = read_json_object(&run_path.join("envelope.json"));
            let result = read_json_object(&run_path.join("result.json"));

            runs.push(RunRow {
                id: file_name_string(&run_path),
                persona: string_field(&envelope, "persona", UNKNOWN),
                style: string_field(&envelope, "style", UNKNOWN),
                shard: string_field(&envelope, "primary_shard", UNKNOWN),
                status: string_field(&result, "status", "in-progress"),
                gates_run: array_len(&result, "gates_run"),
                source: "live".to_string(),
            });
        }
    }

    let docs_ledger = read_json(&repo_root.join(".jules/docs/ledger.json"));
    if let Some(entries) = docs_ledger.as_array() {
        for entry in entries.iter().filter_map(Value::as_object) {
            let run_id = string_field_map(entry, "run_id", UNKNOWN);
            let env_path = repo_root.join(format!(".jules/docs/envelopes/{run_id}.json"));
            let env_data = if env_path.exists() {
                read_json_object(&env_path)
            } else {
                serde_json::Map::new()
            };

            runs.push(RunRow {
                id: run_id,
                persona: first_non_empty(&[
                    string_field_map(&env_data, "persona", ""),
                    string_field_map(entry, "persona", ""),
                    string_field_map(entry, "lane", ""),
                    UNKNOWN.to_string(),
                ]),
                style: first_non_empty(&[
                    string_field_map(&env_data, "style", ""),
                    string_field_map(entry, "style", ""),
                    UNKNOWN.to_string(),
                ]),
                shard: first_non_empty(&[
                    string_field_map(&env_data, "primary_shard", ""),
                    string_field_map(entry, "target", ""),
                    UNKNOWN.to_string(),
                ]),
                status: "historical".to_string(),
                gates_run: array_len_map(&env_data, "receipts")
                    .or_else(|| array_len_map(entry, "receipts"))
                    .unwrap_or(0),
                source: "docs".to_string(),
            });
        }
    }

    let quality_ledger = read_json(&repo_root.join(".jules/quality/ledger.json"));
    if let Some(entries) = quality_ledger.get("runs").and_then(Value::as_array) {
        for entry in entries.iter().filter_map(Value::as_object) {
            let run_id = string_field_map(entry, "run_id", UNKNOWN);
            let env_path = repo_root.join(format!(".jules/quality/envelopes/{run_id}.json"));
            let env_data = if env_path.exists() {
                read_json_object(&env_path)
            } else {
                serde_json::Map::new()
            };

            let desc = string_field_map(entry, "description", "");
            let mut persona = string_field_map(&env_data, "persona", UNKNOWN);
            if persona == UNKNOWN && desc.contains("Gatekeeper") {
                persona = "Gatekeeper".to_string();
            }

            runs.push(RunRow {
                id: run_id,
                persona,
                style: string_field_map(&env_data, "style", UNKNOWN),
                shard: first_non_empty(&[
                    string_field_map(&env_data, "primary_shard", ""),
                    string_field_map(entry, "target", ""),
                    UNKNOWN.to_string(),
                ]),
                status: "historical".to_string(),
                gates_run: array_len_map(&env_data, "receipts")
                    .or_else(|| array_len_map(entry, "receipts"))
                    .unwrap_or(0),
                source: "quality".to_string(),
            });
        }
    }

    Ok(runs)
}

fn friction_metadata(path: &Path) -> Result<FrictionRow> {
    let content = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let lines: Vec<&str> = content.lines().collect();
    let mut row = FrictionRow {
        id: path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or(UNKNOWN)
            .to_string(),
        persona: UNKNOWN.to_string(),
        style: UNKNOWN.to_string(),
        shard: UNKNOWN.to_string(),
        status: "open".to_string(),
        summary: String::new(),
    };

    for line in lines.iter().take(24) {
        let stripped = line.trim().trim_matches('*');
        let Some((key, value)) = stripped.split_once(':') else {
            continue;
        };
        let key = key.trim().to_lowercase().replace(' ', "_");
        let value = value.trim().trim_matches('*').trim();
        if value.is_empty() {
            continue;
        }
        match key.as_str() {
            "id" => row.id = value.to_string(),
            "persona" => row.persona = value.to_string(),
            "style" => row.style = value.to_string(),
            "shard" | "surface" | "component" => row.shard = value.to_string(),
            "status" => row.status = value.to_string(),
            "summary" => row.summary = value.to_string(),
            _ => {}
        }
    }

    for heading in ["## Problem", "**Problem:**", "**Description:**"] {
        let Some((_, after)) = content.split_once(heading) else {
            continue;
        };
        if let Some(summary) = after
            .lines()
            .map(|line| line.trim().trim_start_matches('-').trim())
            .find(|line| !line.is_empty())
        {
            row.summary = summary.to_string();
            break;
        }
    }

    if row.summary.is_empty()
        && let Some(summary) = lines
            .iter()
            .map(|line| line.trim())
            .find(|line| !line.is_empty() && !line.starts_with('#') && !line.contains(':'))
    {
        row.summary = summary.to_string();
    }

    Ok(row)
}

fn sorted_dirs(path: &Path) -> Result<Vec<PathBuf>> {
    let mut dirs = Vec::new();
    for entry in fs::read_dir(path).with_context(|| format!("read dir {}", path.display()))? {
        let entry = entry.with_context(|| format!("read dir entry in {}", path.display()))?;
        if entry
            .file_type()
            .with_context(|| format!("read type for {}", entry.path().display()))?
            .is_dir()
        {
            dirs.push(entry.path());
        }
    }
    dirs.sort_by_key(|path| file_name_string(path));
    Ok(dirs)
}

fn sorted_markdown_files(path: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    for entry in fs::read_dir(path).with_context(|| format!("read dir {}", path.display()))? {
        let entry = entry.with_context(|| format!("read dir entry in {}", path.display()))?;
        if !entry
            .file_type()
            .with_context(|| format!("read type for {}", entry.path().display()))?
            .is_file()
        {
            continue;
        }
        let entry_path = entry.path();
        if entry_path.extension().and_then(|ext| ext.to_str()) == Some("md") {
            files.push(entry_path);
        }
    }
    files.sort_by_key(|path| file_name_string(path));
    Ok(files)
}

fn read_json(path: &Path) -> Value {
    fs::read_to_string(path)
        .ok()
        .and_then(|body| serde_json::from_str(&body).ok())
        .unwrap_or(Value::Object(serde_json::Map::new()))
}

fn read_json_object(path: &Path) -> serde_json::Map<String, Value> {
    read_json(path).as_object().cloned().unwrap_or_default()
}

fn string_field(map: &serde_json::Map<String, Value>, key: &str, default: &str) -> String {
    string_field_map(map, key, default)
}

fn string_field_map(map: &serde_json::Map<String, Value>, key: &str, default: &str) -> String {
    map.get(key)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .unwrap_or(default)
        .to_string()
}

fn array_len(map: &serde_json::Map<String, Value>, key: &str) -> usize {
    array_len_map(map, key).unwrap_or(0)
}

fn array_len_map(map: &serde_json::Map<String, Value>, key: &str) -> Option<usize> {
    map.get(key).and_then(Value::as_array).map(Vec::len)
}

fn first_non_empty(values: &[String]) -> String {
    values
        .iter()
        .find(|value| !value.is_empty())
        .cloned()
        .unwrap_or_default()
}

fn file_name_string(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_string()
}

fn markdown_cell(value: &str) -> String {
    let text = if value.is_empty() { UNKNOWN } else { value };
    text.replace('\n', " ").trim().replace('|', "\\|")
}

fn workspace_root() -> Result<PathBuf> {
    let metadata = cargo_metadata::MetadataCommand::new()
        .no_deps()
        .exec()
        .context("locate workspace root")?;
    Ok(metadata.workspace_root.into_std_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_cell_escapes_pipes_and_newlines() {
        assert_eq!(markdown_cell("a|b\nc"), "a\\|b c");
        assert_eq!(markdown_cell(""), UNKNOWN);
    }

    #[test]
    fn first_non_empty_selects_first_value() {
        assert_eq!(
            first_non_empty(&[String::new(), "docs".to_string(), UNKNOWN.to_string()]),
            "docs"
        );
    }
}
