name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I'd like `tokmd` to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've tried?

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would you use this feature? Who else might benefit?
      placeholder: |
        Example workflow:
        1. ...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of tokmd does this relate to?
      options:
        - CLI commands
        - Output formats (Markdown, JSON, CSV)
        - Analysis features
        - Performance
        - Documentation
        - Other
