name: Feature Request
description: Suggest a new feature or enhancement for tokmd
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

        **Before submitting**, please check:
        - [ ] I searched [existing issues](https://github.com/EffortlessMetrics/tokmd/issues) for similar requests
        - [ ] I reviewed the [ROADMAP.md](https://github.com/EffortlessMetrics/tokmd/blob/main/ROADMAP.md) for planned features

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem does this solve? Is this related to a frustration with the current behavior?
        A clear problem statement helps us understand the motivation.
      placeholder: |
        I'm trying to accomplish X, but tokmd currently doesn't support...

        OR

        When analyzing large monorepos, I find it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        How would you like this to work? Be as specific as possible.
        Include example commands, flags, or output formats if applicable.
      placeholder: |
        I'd like `tokmd` to support a `--foo` flag that...

        Example usage:
        ```bash
        tokmd analyze --foo bar
        ```

        Expected output:
        ```json
        { "foo": "bar" }
        ```
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of tokmd does this relate to?
      multiple: true
      options:
        - CLI commands / flags
        - Output formats (Markdown, JSON, CSV)
        - Analysis presets (health, risk, supply, etc.)
        - Enrichers (git, content, imports)
        - Gate / policy evaluation
        - Badge generation
        - Performance
        - Documentation
        - Library API (tokmd-core)
        - Language bindings (Python, Node.js)
        - GitHub Action
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this change existing behavior or output formats?
      options:
        - "No - purely additive"
        - "Yes - changes existing output structure"
        - "Yes - changes CLI interface"
        - "Yes - changes schema version"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: |
        Describe your workflow. How would you use this feature in practice?
        Who else might benefit from this?
      placeholder: |
        Example workflow:
        1. Run `tokmd analyze` on a PR
        2. Use the new output to...
        3. This would help teams who...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Any alternative solutions or workarounds you've tried?
        This helps us understand the problem space better.
      placeholder: |
        I tried using `tokmd export | jq ...` but it doesn't quite work because...

        OR

        Other tools like X do this by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority to You
      description: How important is this feature to your workflow?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking a use case I need
    validations:
      required: true

  - type: dropdown
    id: contribute
    attributes:
      label: Willingness to Contribute
      description: Would you be interested in implementing this feature?
      options:
        - "Yes - I'd like to implement this"
        - "Yes - I can help with testing/review"
        - "Maybe - I'd need guidance"
        - "No - I'm requesting this feature"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that would help.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
